tools:
  exceptions:
  logging:
  ci:
    frontend: https://github.com/dcsil/Cyberity-App/actions
    backend: https://github.com/dcsil/Cyberity-App/actions

services:
  production: http://cyberity.herokuapp.com/

docs:
  getting_started: ./README.md

commands:
  bootstrap: source run bootstrap
  server:
    dev: source run dev server
    prod: source run prod
  client: source run dev client
  test: source run test

