tools:
  exceptions: https://sentry.io/organizations/dcsil/issues/?project=5450615
  logging: https://my.papertrailapp.com/systems/cyberity/events
  ci:
    frontend: https://github.com/dcsil/Cyberity-App/actions
    backend: https://github.com/dcsil/Cyberity-App/actions

services:
  production: http://cyberity.herokuapp.com/

docs:
  getting_started: ./README.md

commands:
  bootstrap: source run bootstrap
  server:
    dev: source run dev server
    prod: source run prod
  client: source run dev client
  test: source run test
  database:
    start: sudo service mongodb start
    stop: sudo service mongodb stop
